version: "3"
# Defines which compose version to use
services:
  # Services line define which Docker images to run. In this case, it will be MySQL server and WordPress image.
  db:
    image: mysql:5.7
    container_name: mariadb
    # image: mysql:5.7 indicates the MySQL database container image from Docker Hub used in this installation.
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MyR00tMySQLPa$$5w0rD
      MYSQL_DATABASE: MyWordPressDatabaseName
      MYSQL_USER: MyWordPressUser
      MYSQL_PASSWORD: Pa$$5w0rD
      # Previous four lines define the main variables needed for the MySQL container to work: database, database username, database user password, and the MySQL root password.
    volumes:
      - mysql:/var/lib/mysql
  wordpress:
    depends_on:
      - db
    image: wordpress:6.1.1
    container_name: ssas_testing
    restart: always
    # Restart line controls the restart mode, meaning if the container stops running for any reason, it will restart the process immediately.
    ports:
      - "9005:80"
      # The previous line defines the port that the WordPress container will use. After successful installation, the full path will look like this: http://localhost:9050
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: MyWordPressUser
      WORDPRESS_DB_PASSWORD: Pa$$5w0rD
      WORDPRESS_DB_NAME: MyWordPressDatabaseName
      WORDPRESS_CONFIG_EXTRA: |
        define('DISABLE_WP_CRON', true);
        define('WP_MEMORY_LIMIT', '512M');
        define('DISALLOW_FILE_EDIT', true);
        define('DISALLOW_FILE_MODS', true);
    #The defines above represent limitations to wordpress functionality in order to prevent attacks in site.
    # Similar to MySQL image variables, the last four lines define the main variables needed for the WordPress container to work properly with the MySQL container.
    volumes:
      - .:/var/www/html
volumes:
  mysql:
